## import

In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Basic grammer

In [ ]:
# print functions represent arg.
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [ ]:
# explain a print function
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [5]:
3 + 5

8

In [7]:
"hello" + " " + "world"

'hello world'

In [ ]:
# what differences with tuple and list?
# 
x = [3, 4, 5]
x

[3, 4, 5]

In [9]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

In [10]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])
x + y

array([ 7, 13, 12])

In [ ]:
# You can make vector using numpy.
# 2 * 2 vector
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
x.ndim

2

In [14]:
x.dtype

dtype('int64')

In [15]:
np.array?

Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [ ]:
# maybe represent 2*2 dimensions
x.shape

(2, 2)

In [ ]:
# Adding all elements.
x = np.array([1, 2, 3, 4])
x.sum()

np.int64(10)

In [28]:
x = np.array([1, 2, 3, 4, 5, 6])
print("begging x:\n", x)
# 1*6 vector reshape to 2*3 one
x_reshape = x.reshape((2, 3))
print('reshped x\n', x_reshape)

begging x:
 [1 2 3 4 5 6]
reshped x
 [[1 2 3]
 [4 5 6]]


In [23]:
# [x, y] represent x, y dimensio number.
x_reshape[0, 0]

np.int64(1)

In [25]:
# maybe display results is 2
# I think first position is 1. but, first position is 0. so, the result by under codes is 6.
x_reshape[1, 2]

np.int64(6)

In [26]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [29]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [30]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [33]:
x**2

array([ 1,  4,  9, 16, 25, 36])

In [34]:
x**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [ ]:
x = np.random.normal(size=50)
x
# 1*50 vector

array([ 1.72003602, -1.4661482 ,  0.05982732, -0.62289303,  1.16203793,
        0.20243274,  0.64158629,  0.89803335,  0.8538309 , -1.34374838,
        0.71697541, -0.240111  , -0.17837764, -1.02229553,  1.17389056,
        0.1137004 ,  0.85595578,  0.46542041, -0.19048212, -0.7926146 ,
        1.93378612, -1.8316048 , -1.47677326, -1.4961693 , -1.31199307,
        0.68769236, -1.06790869,  0.04067546,  0.4039142 , -0.4633459 ,
        1.65452459, -1.36818562,  0.73710333, -0.05912993,  0.36863158,
        1.51127518,  0.06347677, -0.25287273,  0.19987139,  0.7514543 ,
        0.12576256,  0.46590002, -0.4731617 ,  0.38452496, -2.23196999,
        0.25364619,  0.97786593, -1.35016685, -1.0391256 ,  1.04466536])

In [37]:
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([51.83003363, 47.77316782, 50.13704693, 47.32827694, 53.09269202,
       51.3010113 , 52.24527734, 51.38142125, 50.97470978, 49.91265202,
       51.39941817, 50.04998049, 49.77232892, 47.70517694, 51.76355255,
       49.97776316, 49.78513522, 51.70673783, 48.53405598, 47.47209961,
       52.95921218, 49.50092585, 48.5761074 , 49.30729026, 47.03995781,
       50.35068594, 48.95008082, 51.93726306, 50.79577222, 49.81509196,
       50.51948602, 49.82078069, 49.88573151, 50.63851369, 50.14347252,
       52.1626205 , 50.9488343 , 50.53922849, 50.90416073, 51.57957401,
       50.1223998 , 51.9268017 , 48.67078631, 50.76801886, 47.73106428,
       48.82392342, 49.07582464, 48.65101894, 50.30445622, 50.0562956 ])

In [ ]:
np.corrcoef(x, y)
# The corrcoef function means calculate correlation.

array([[1.        , 0.71936446],
       [0.71936446, 1.        ]])

In [46]:
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [50]:
rng = np.random.default_rng(3)
y = rng.standard_normal(10)
np.mean(y), y.mean()

(np.float64(-0.1126795190952861), np.float64(-0.1126795190952861))

In [ ]:
# Note: can calculate mean, std
# np.var means variance(分散)
# variance: $$V = E[X^2] - (E[X])^2$$
print(f"{np.var(y), y.var(), np.mean((y - y.mean()) ** 2)}")
print(f"sqrt: {np.sqrt(np.var(y))}, std: {np.std(y)}")

(np.float64(2.7243406406465125), np.float64(2.7243406406465125), np.float64(2.7243406406465125))
sqrt: 1.6505576756498128, std: 1.6505576756498128


In [58]:
# 10*3 matrix of N(0, 1)
# N(x, y) means that x is means, y is std, N is 
X = rng.standard_normal((10, 3))
X

array([[ 0.27644576,  0.70054489, -0.44476746],
       [-1.07640584,  0.02612483, -0.05274731],
       [ 1.40559817,  0.74740799,  0.19381565],
       [ 1.11163321, -0.20552305, -0.92589957],
       [ 0.58405831,  0.58253842, -0.21482891],
       [-0.78280858,  0.22915391, -2.49389428],
       [ 0.69012477,  0.49136826, -1.63885714],
       [ 0.06135351, -0.96409966,  0.75722104],
       [-2.03416727, -0.91449454,  0.70957999],
       [ 1.15640105, -2.15800538, -0.49803984]])

In [64]:
# Note: under two codes results in the same num.
print(X.mean(axis=0))
print(X.mean(0))

[ 0.13922331 -0.14649843 -0.46084178]
[ 0.13922331 -0.14649843 -0.46084178]


## Graphicals